KhronosGroup/SYCL_Reference

source/iface/queue.rst

update queue to 2020

---

source/examples/context.cpp
source/examples/context.out
source/iface/context.rst

Basic example for printing all the devices in a simple context

Add basic SYCL context example

---

.pre-commit-config.yaml
source/examples/gpu-selector.cpp
source/examples/stream.out
source/iface/buffer.rst
source/iface/common-reference.rst
source/iface/device-selector.rst
source/iface/device.rst
source/iface/exception.rst
source/iface/platform.rst
source/iface/stream.rst

Martin example consistency

---

source/iface/id.rst

Fix description of sycl::id

---

source/conf.py
source/namespaces.rst

Updated Namespaces section
Issue: RF-02

Update "Namespaces" to SYCL-2020

---

source/conf.py
source/examples/event-elapsed-time.cpp
source/examples/event-elapsed-time.out
source/iface/event.rst
source/spelling_wordlist.txt

[KHRGA-59] Update Events from Runtime Classes

---

source/conf.py
source/examples/std-vector.out
source/iface/usm_allocations.rst
source/spelling_wordlist.txt

[KHRGA-35] Updated USM allocations and allocator interface

---

source/conf.py
source/iface/device.rst
source/iface/usm_allocations.rst
source/iface/usm_basic_concept.rst
source/iface/usm_pointer_queries.rst

[KHRGA-36] Updated USM Pointer Queries

---

source/conf.py
source/examples/usm-device.cpp
source/examples/usm-shared.cpp
source/iface/queue.rst
source/iface/usm_allocations.rst
source/iface/usm_basic_concept.rst
source/spelling_wordlist.txt

Issue: KHRGA-34
The "USM Basic Concept" structure was discussed in the issue https://github.com/KhronosGroup/SYCL_Reference/issues/78

[KHRGA-34] Updated USM Basic Concept

---

source/iface/usm_allocations.rst
source/spelling_wordlist.txt

[KHRGA-65] Updated USM deallocation functions

---

source/conf.py
source/iface/common-byval.rst
source/spelling_wordlist.txt

[KHRGA-25] Updated CI Common by-value semantics

---

source/conf.py
source/iface/host_accessor.rst
source/spelling_wordlist.txt

[KHRGA-76] Updated host accessors in Data access

---

source/conf.py
source/iface/image-sampler.rst

[KHRGA-33] Updated DA Image Samplers

---

source/conf.py
source/iface/synchronization-primitives.rst

[KHRGA-82] Updated DA Synchronization primitives

---

source/conf.py
source/iface/local_accessor.rst
source/spelling_wordlist.txt

[KHRGA-77] Updated local accessors from Data access chapter

---

source/iface/accessor-concept.rst
source/iface/sampled-image-accessor.rst

[KHRGA-79] Updated DA sampled image accessor

---

source/conf.py
source/iface/range.rst
source/spelling_wordlist.txt

[KHRGA-37] Updated range classes

---

source/conf.py
source/iface/id.rst
source/spelling_wordlist.txt

[KHRGA-39] Updated EP id classes

---

source/conf.py
source/iface/address-space.rst
source/spelling_wordlist.txt

[KHRGA-31] Updated DA Address Space Classes

---

source/conf.py
source/iface/h_item.rst

[KHRGA-86] Updated EP h_item classes

---

source/conf.py
source/iface/sub_group.rst

[KHRGA-41] Updated EP sub group class

---

source/data-types.rst
source/iface/math-array-types.rst
source/iface/scalar-types.rst
source/iface/vector-types.rst
source/parallelism.rst

Issue: KHRGA-88
Skeleton discussion: https://github.com/KhronosGroup/SYCL_Reference/issues/118

[KHRGA-88] New skeleton for the "Data types" chapter

---

source/iface/stream.rst
source/iface/stream_manipulator.rst
source/io.rst

Issue: KHRGA-94
Skeleton discussion: https://github.com/KhronosGroup/SYCL_Reference/issues/123

[KHRGA-94] New skeleton for the "Stream" chapter

---

source/backends.rst
source/class-availability.rst
source/generic-and-non-generic.rst
source/iface/atomic-types.rst
source/index.rst
source/synchronization.rst

Issue: KHRGA-97
Discussion: https://github.com/KhronosGroup/SYCL_Reference/issues/130
Also includes Atomic types (as discussed in the https://github.com/KhronosGroup/SYCL_Reference/issues/124).

[KHRGA-97] Added "Backends", "Class availiability", and "Generic vs non-generic SYCL" chapters

---

source/conf.py
source/iface/reduction-variables.rst

[KHRGA-48] Updated EP reduction variables

---

source/conf.py
source/iface/device_image.rst

[KHRGA-44] Updated EP device image class

---

source/conf.py
source/examples/handler-copy.cpp
source/examples/handler-copy.out
source/examples/host-task.cpp
source/examples/host-task.out
source/iface/command-group-handler.rst
source/iface/host-task-basic.rst
source/iface/specialization-constants.rst
source/spelling_wordlist.txt

[KHRGA-46] Updated EP command group handler

---

source/conf.py
source/iface/kernel-bundles.rst
source/spelling_wordlist.txt

[KHRGA-43] Updated EP kernel bundles

---

source/conf.py
source/examples/stream.cpp
source/iface/common-byval.rst
source/iface/common-reference.rst
source/iface/param_traits.rst
source/iface/properties.rst
source/iface/stream.rst

[KHRGA-53] Updated IO Stream class

---

source/conf.py
source/iface/scalar-types.rst

[KHRGA-50] Updated DT scalar types

---

source/conf.py
source/iface/stream_manipulator.rst

[KHRGA-98] Updated IO Stream manipulators

---

source/conf.py
source/iface/exception.rst
source/iface/queue.rst
source/spelling_wordlist.txt

[KHRGA-49] Updated EH Exceptions

---

source/class-availability.rst
source/conf.py

[KHRGA-107] Updated Class availability

---

source/generic-and-non-generic.rst
source/spelling_wordlist.txt

[KHRGA-109] Update GNG generic vs non generic sycl

---

source/conf.py
source/iface/math-array-types.rst
source/spelling_wordlist.txt

[KHRGA-92] Updated DT math array types

---

source/backends.rst
source/conf.py
source/spelling_wordlist.txt

[KHRGA-105] Updated BAC backends class

---

source/conf.py
source/examples/atomic.cpp
source/examples/atomic.out
source/iface/atomic_ref.rst

[KHRGA-52] Updated S&A atomic_ref class

---

source/conf.py
source/iface/host-task-basic.rst

[KHRGA-121] Updated HT basic concept

---

source/conf.py
source/iface/device_event.rst

[KHRGA-101] Updated S&A device_event class

---

source/conf.py
source/iface/interaction-with-host-code.rst

[KHRGA-102] Updated SA Interaction with Host Code

---

source/conf.py
source/iface/host-task-add-to-handler.rst
source/spelling_wordlist.txt

[KHRGA-123] Updated additions of handler

---

source/iface/interop_handle.rst

[KHRGA-122] Updated HT interop handle

---

source/conf.py
source/iface/atomic-types.rst

[KHRGA-103] Updated AO atomic types

---

source/conf.py
source/iface/group-functions.rst

[KHRGA-111] Updated group functions

---

source/conf.py
source/iface/function-objects.rst

[KHRGA-110] Updated BIF function objects

---

source/iface/common-functions.rst
source/spelling_wordlist.txt

[KHRGA-117] Updated BiF Common functions

---

source/conf.py
source/iface/math-functions.rst
source/spelling_wordlist.txt

[KHRGA-113] Updated BiF Math functions

---

source/conf.py
source/iface/geometric-functions.rst
source/iface/geometric.rst
source/spelling_wordlist.txt

[KHRGA-118] Updated BiF Geometric functions

---

source/namespaces.rst

Issue: KHRGA-128
Removed the second line as discussed.

[KHRGA-128] Fixed namespaces.rst file

---

source/conf.py
source/iface/integer-functions.rst

[KHRGA-116] Updated BIF integer functions

---

source/iface/native-prec-math-func.rst

[KHRGA-114] Updated BIF native precision math functions

---

source/iface/half-prec-math-func.rst

[KHRGA-115] Updated BIF half precision math functions

---

source/iface/function-objects.rst
source/iface/group-functions.rst

[KHRGA-132] Updated BIF fully qualified names

---

source/iface/math-array-types.rst
source/iface/scalar-types.rst
source/iface/vector-types.rst

[KHRGA-135] Updated DT fully qualified names

---

source/iface/host-task-basic.rst
source/iface/interop_handle.rst

[KHRGA-133] Updated HT fully qualified names

---

source/iface/backend_interop.rst
source/iface/context.rst
source/iface/device-selector.rst
source/iface/device.rst
source/iface/event.rst
source/iface/platform.rst
source/iface/queue.rst

Issue: KHRGA-130
**Updated files:**
- context.rst
- device-selector.rst
- event.rst
- device.rst
- platform.rst
- queue.rst

[KHRGA-130] Fixing Runtime Classes Chapter

---

source/iface/command-accessor.rst
source/iface/host_accessor.rst
source/iface/local_accessor.rst
source/iface/sampled-image-accessor.rst
source/iface/unsampled-image-accessor.rst

[KHRGA-129] Updated DA fully qualified names

---

source/iface/device_image.rst
source/iface/group.rst
source/iface/h_item.rst
source/iface/id.rst
source/iface/kernel-bundles.rst
source/iface/nd_item.rst

Issue: KHRGA-131
Updated files:
- device_image.rst
- group.rst
- h_item.rst
- id.rst
- kernel-bundles.rst
- nd_item.rst

[KHRGA-131] Fix Runtime Classes chapter, part 1

---

source/iface/range.rst
source/iface/reduction-variables.rst
source/iface/specialization-constants.rst
source/iface/sub_group.rst

[KHRGA-145] Updated EP fully qualified names 2

---

.github/workflows/checks.yml

Update GitHub actions to latest version.
Update Python used in actions to latest version.

Update GitHub action versions
